import puppeteer from 'puppeteer-core';
const CH='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const b=await puppeteer.launch({executablePath:CH,headless:'new'});
const p=await b.newPage(); await p.setViewport({width:1280,height:720});
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto('http://localhost:5321/',{waitUntil:'networkidle0'});
await p.waitForFunction(()=>document.body.dataset.ready==='true',{timeout:30000});
const d=await p.evaluate(()=>({scene:__dash.scene,objects:__dash.objects,controls:__dash.controls,unknown:__dash.unknownClasses,vis:__dash.unresolvedVisuals,mi:__dash.missingImages,ph:__dash.placeholders,fps:__dash.fps}));
console.log('default route',JSON.stringify(d),'errs',errs.length);
await b.close();
